name: Auto Build, Push and Deploy

on:
  push:
    branches: 
      - develop
      - master

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest
    # Set environment based on the branch
    environment: ${{ github.ref == 'refs/heads/master' && 'prod' || 'test' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment-specific image name
        id: image-name
        run: |
          ENV="${{ github.ref == 'refs/heads/master' && 'prod' || 'test' }}"
          REPO_NAME=$(echo "${{ env.BASE_IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_TAG=${{ env.REGISTRY }}/${REPO_NAME}-${ENV}:latest" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.image-name.outputs.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            DB_CONNECTION=pgsql
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ vars.DB_PORT }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: Trigger Render Deployment
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK_URL" 